# Grant argo SA "view-like" access to the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-creator
  namespace: {{ namespace }}
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    ansible/role: argo-workflows
  name: workflow-creator
  namespace: {{ namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-creator
subjects:
- kind: ServiceAccount
  name: workflow-creator
  namespace: {{ namespace }}
